### ISSUE TITLE
R.swift not generated

### ISSUE THREAD

**Issue by erfanwakka** [mac-cain13/R.swift#484]
Hi I have problem in using R.swift. I do every step of installing R.swift using Pods in Xcode 10 but I have this error and no R.generated.swift generated : 
`[R.swift] The folder “R.generated.swift” doesn’t exist.`

**Comment by tomlokhorst** [comment]
What is the build step script you're using?

Does it match the [installation instructions](https://github.com/mac-cain13/R.swift#cocoapods-recommended):
```bash
"$PODS_ROOT/R.swift/rswift" generate "$SRCROOT/R.generated.swift"
```

**Comment by amrObjection** [comment]
me too have the same problem three times follow the instructions in xcode 10 and 9.4 , and every time this error happen .
error: [R.swift] The folder “R.generated.swift” doesn’t exist.
Command /bin/sh emitted errors but did not return a nonzero exit code to indicate failure

**Comment by mac-cain13** [comment]
What version of R.swift are you using? It sounds like you're using an older version that expects to receive a folder instead of a file.

**Comment by amrObjection** [comment]
4.0.0 for swift 4.1
and 5.0.0 for 4.2

**Comment by ferasallaou** [comment]
I have the same issue with xCode 10.1, 4.0.0 for RSwift.

**Comment by erfanwakka** [comment]
> Are you using the latest version of R.swift? What is the build step script you're using?
> 
> Does it match the [installation instructions](https://github.com/mac-cain13/R.swift#cocoapods-recommended):
> 
> ```shell
> "$PODS_ROOT/R.swift/rswift" generate "$SRCROOT/R.generated.swift"
> ```

I exactly do the installation steps correctly

**Comment by ferasallaou** [comment]
Still getting this error
    error: [R.swift] The folder “R.generated.swift” doesn’t exist.
    Command PhaseScriptExecution emitted errors but did not return a nonzero exit code to indicate 
     failure

@erfanwakka

**Comment by ostatnicky** [comment]
I had the same problem but update R.swift pod to 5.0.2 (I had 4.0.0) solved it.

**Comment by ttorbik** [comment]
Same issue, any update?

**Comment by wei20** [comment]
Same here

**Comment by tomlokhorst** [comment]
Can any of you provide a proper reproduction path?

Are you using the latest version?
What is the build script you're using?
What are the error messages that are being emitted?
What did you change from when it did work? (if applicable)

Without this, there's nothing much I can look into, as this hasn't happend in any of the many R.swift projects I'm using.

**Comment by caloon** [comment]
Having the same issue:
`[R.swift] The folder “R.generated.swift” doesn’t exist.` 

Using R.swift version 4.0.0 in an app with Swift 3 and Xcode 10.1. I used the following Build Script. `"$PODS_ROOT/R.swift/rswift" generate "$SRCROOT/R.generated.swift"`

When I create an empty `R.generated.swift` in SRCROOT on my own, the error message changes to 
`The file “R.generated.swift” couldn’t be saved in the folder “R.generated.swift”.`

Is R.swift maybe missing required rights to write on disk?

**Comment by hamedaakhlaghi** [comment]
I had the same issue, with removing all Xcode cached data from `library` it resolved

**Comment by mac-cain13** [comment]
Assuming this is solved now. Feel free to open a new issue if R.swift doesn't generate the file for you correctly.

**Comment by benSmith1981** [comment]
This isn't solved. I Updated to swift 5 and R.Swift 5.0.3 and i cannot regenerate my r file. I followed the latest instructions https://github.com/mac-cain13/R.swift/tree/v4.0.0#cocoapods-recommended. I saw the last comment form @hamedaakhlaghi but I don't know what cache folders you mean exactly? Just derived data? This is most frustrating issue... please help.

**Comment by benSmith1981** [comment]
Ok fixed... after hours of puzzling. I just deleted everything from the R.generated file, but kept the file in the same path as specified in the run script phase, and it regenerated the code. BUT. If i delete the file it won't regenerate it very easily, maybe this is a caching thing in xcode. Have no idea @mac-cain13 ?

**Comment by tomlokhorst** [comment]
Note that if you're using R.swift 5, you should use the latest installation instructions https://github.com/mac-cain13/R.swift#cocoapods-recommended (not the ones for R.swift 4).

If you're upgrading from R.swift 4 to R.swift 5, see the migration guide: https://github.com/mac-cain13/R.swift/blob/master/Documentation/Migration.md#upgrading-to-50

**Comment by mac-cain13** [comment]
@benSmith1981 makes me sad to hear R.swift did cost you hours of puzzling.

Could you confirm that you where using the R.swift 5 instructions/migration steps? Is it still the case that the generated file doesn't update or is it now fixed since you once emptied the file?

It would help enormously if I can get my hands on a demo or real project where this is going wrong so we can investigate. It's probably just a tiny thing that's misconfigured but very hard to find once it's broken. Do you think it's possible to share a project in the same broken state you experienced?

**Comment by evgenijkrivelev17** [comment]
I had the same problem. But after some time, I just created empty file, and after it, I rebuilt project and that was worked. But I have another problem. Now R.swift don't see new images, fonts, and localization string in my project.
