### ISSUE TITLE
Refactor if/else tree that caused stand alone images to be skipped

### ISSUE THREAD

**Issue by CraigsOverItAll** [mac-cain13/R.swift#498]
`R.generated.swift` would contain both `R.file` and `R.image` references to "stand alone" (i.e. not in an asset catalogue) using v4.x, with the optimisation in PR #451, specifically commit 4fc7d553 this no longer happens.

The impact is that any API's that take a `URL` to an image resource rather than a `UIImage` can't use `R.swift`.

I've made a quick PR #497 to temporarily patch `rswift` to restore the previous behaviour.

I'm guessing in the long run it would be better in general to expose a `URL` attribute on the `R.image` entries.

**Comment by mac-cain13** [comment]
Hi Craig! Thanks for using R.swift and taking the time to report this issue and even submit a PR to fix it. Very helpful that you also have referenced the exact commit breaking this behavior.

This is an unintended breaking change that should not have happend, I think your PR is a good workaround that we can use. I will merge and release this asap.

After that I think we should remove the assumption from this code that if a resource matches a certain type it cannot also be of another type. I think this can cause more bugs in the future and the performance gain will probably be minimal in most cases.

**Comment by mac-cain13** [comment]
So, R.swift 5.0.3 with the fix is released for some some days now. I would like to keep this issue open as a reminder that we need to refactor the if/else tree that caused this issue.

For reference that if/else tree can be found here: https://github.com/mac-cain13/R.swift/commit/4fc7d5536d8d69db6d940c3bd3c2f51a947aa1a7#diff-ea7e2f5adb89f7fbf2fb90c1a2586281R39

**Comment by vladimir-ionita** [comment]
I'm afraid this is still an issue. Fonts are files are not parsed in my project, although on version 4 it worked corectly
