### ISSUE TITLE
SPM Integration doesn't work on Xcode 14.3

### ISSUE THREAD

**Issue by dev4dev** [mac-cain13/R.swift#822]
I have an issue with integrating the latest version in Xcode 14.3. These menu items are missing, therefore all `bugfix workaround` doesn't work for me and a project doesn't compile as `R.` is not defined

Screenshot from (14.2)
![image](https://user-images.githubusercontent.com/722407/229577400-622cfe7b-f26f-4880-ae8e-9312a1806fbc.png)

**Comment by jeannustre** [comment]
I can also reproduce this. Moving back to Xcode 14.2 as a workaround.

**Comment by jhpassion0621** [comment]
Hi, You can use this as workaround

https://github.com/mac-cain13/R.swift/issues/813

**Comment by tomlokhorst** [comment]
This seems to be a bug in Xcode 14.3.

The shortest workaround I've found is to manually do these steps:

1. Place a Package.swift file in the same directory as YourProject.xcodeproj with this content:
```swift
// swift-tools-version:5.6
import PackageDescription
let package = Package(name: "", dependencies: [ .package(url: "https://github.com/mac-cain13/R.swift", from: "7.3.0") ])
```
2. Run: `swift run rswift modify-xcode-packages --xcodeproj YourProject.xcodeproj --target YourTarget`
3. (Optional) Remove the Package.swift file again.

This does the same thing as the `RswifModifyXcodePackage` command does in Xcode 14.2.

**Comment by egesucu** [comment]
This issue has been resolved with Xcode 14.3.1 RC, as I checked this again.
<img width="567" alt="SS" src="https://github.com/mac-cain13/R.swift/assets/16636371/27fc9856-99ab-4ab0-b8ba-9318990d829f">

**Comment by dev4dev** [comment]
yep, that particular issue is mentioned as fixed in a changelog. there are other bugs fixed that I had, so waiting for a release 🤞🏻

**Comment by tomlokhorst** [comment]
This was a bug in Xcode 14.3, and has been fixed in Xcode 14.3.1

**Comment by olegbraginontarget** [comment]
I'm still getting compiler error about missing R. 

`Cannot find 'R' in scope`

I have Xcode 14.3.1 installed, run the context menu item to run RswiftModifyXcodePackages both from the context menu item and manually as described in workaround above. 

I see both files R.generated.swift generated in correct locations (as it seems), but Xcode still doesn't see those files, thus the project is not compiled. 

My setup: I have a main application with dependent extension. If I build only extension it builds OK, but if I build main app, I still see the error.

**Comment by alpatiev** [comment]
_If anyone is still encountering the problem, the best thing to do is update to 14.3.1._
